"""稳定的 API 业务错误码定义。"""

from enum import StrEnum


class ErrorCode(StrEnum):
    """错误码按责任边界分组，文案变化不影响客户端判断。"""

    REQUEST_BODY_INVALID = "REQUEST_BODY_INVALID"
    QUERY_EMPTY = "QUERY_EMPTY"
    QUERY_TOO_LONG = "QUERY_TOO_LONG"
    QUERY_INVALID = "QUERY_INVALID"

    SQL_FORBIDDEN = "SQL_FORBIDDEN"
    SQL_TABLE_NOT_ALLOWED = "SQL_TABLE_NOT_ALLOWED"
    SQL_VALIDATION_FAILED = "SQL_VALIDATION_FAILED"
    SQL_EXECUTION_FAILED = "SQL_EXECUTION_FAILED"

    MODEL_TIMEOUT = "MODEL_TIMEOUT"
    MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
    VECTOR_SEARCH_FAILED = "VECTOR_SEARCH_FAILED"
    DATABASE_UNAVAILABLE = "DATABASE_UNAVAILABLE"
    QUERY_TIMEOUT = "QUERY_TIMEOUT"
    INTERNAL_ERROR = "INTERNAL_ERROR"
